# Generated by Django 4.1.7 on 2023-03-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_album_player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='parentAlbum',
            field=models.TextField(default='Parent Album'),
        ),
        migrations.AddField(
            model_name='track',
            name='parentSong',
            field=models.TextField(default='Parent Song'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
