# Generated by Django 4.1.7 on 2023-03-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_album_player', '0002_track_parentalbum_track_parentsong_alter_track_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
    ]
